### ISSUE TITLE
Add Zyxel GS-108B support

### ISSUE THREAD

**Issue by samm-git** [illarionov/OpenRRCP#3]
Hi, first of all - thank you for your work,  i found your project when tried to find why my switch sends 0x8899 packets every second or so. So i found that it is RRCP broadcast message and very intestested if i can convert this switch to the managed one. I already removed cooling plate from the chip and found that it is RTL8370N inside, which seems to be not supported. Some other interesting info:

- Switch sends every second or so rccp query and sometime rccp reply (why?). So at least some of the related functionality is enabled. However, it did not matching known RRCP protocol description + padding is strange (0x20)
```
[root@bunny /home/samm/OpenRRCP/bin]# tcpdump -n -x -vvv -i bce0 broadcast
tcpdump: listening on bce0, link-type EN10MB (Ethernet), capture size 65535 bytes
capability mode sandbox enabled
12:38:02.543694 04:bf:6d:26:ac:c7 > ff:ff:ff:ff:ff:ff, RRCP-0x23 reply
	0x0000:  2395 de9a e2e7 8504 bf6d 26ac c702 2020
	0x0010:  2020 2020 2020 2020 2020 2020 2020 2020
	0x0020:  2020 2020 2020 2020 2020 2020 2020
12:38:04.543650 04:bf:6d:26:ac:c7 > ff:ff:ff:ff:ff:ff, RRCP-0x23 reply
	0x0000:  2395 de9a e2e7 8504 bf6d 26ac c702 2020
	0x0010:  2020 2020 2020 2020 2020 2020 2020 2020
	0x0020:  2020 2020 2020 2020 2020 2020 2020
12:38:06.543610 04:bf:6d:26:ac:c7 > ff:ff:ff:ff:ff:ff, RRCP-0x23 reply
	0x0000:  2395 1bde 2d08 b204 bf6d 26ac c702 2020
	0x0010:  2020 2020 2020 2020 2020 2020 2020 2020
	0x0020:  2020 2020 2020 2020 2020 2020 2020
12:38:08.543565 04:bf:6d:26:ac:c7 > ff:ff:ff:ff:ff:ff, RRCP-0x23 query
	0x0000:  2368 1bde 2d08 b204 bf6d 26ac c702 2020
	0x0010:  2020 2020 2020 2020 2020 2020 2020 2020
	0x0020:  2020 2020 2020 2020 2020 2020 2020
12:38:10.543524 04:bf:6d:26:ac:c7 > ff:ff:ff:ff:ff:ff, RRCP-0x23 query
	0x0000:  2368 1bde 2d08 b204 bf6d 26ac c702 2020
	0x0010:  2020 2020 2020 2020 2020 2020 2020 2020
	0x0020:  2020 2020 2020 2020 2020 2020 2020
```
- There is a EEPROM chip on the board, it is HT 24LC32. Near this chip there are 4 soldered pins, no idea what it is. 
- On the back side there are some labels: 
  - **R40** 4k7: enable 8051/NI: Disable 8051, resistor is installed
  - EEPROM **R27**(4k7), FLASH R27NI, resistor is installed
  - **R56**: 24C16:4K7, NI:24C32, resistor not installed

I tried to play with `rtlping` and other tools w/o any luck. Also i did not found datasheet for the RTL8370N on the net, only some sources with registry description in the driver. I do not have any experience with RRCP so not sure what to do next. Could you please advise me something to make it manageable ?

**Comment by akosiaris** [comment]
Hello, just adding that I 've seen similar packets as well. I have no idea what the switches (except that the MAC address is Zyxel) in the network are. I just have access to linux box and run tcpdump to debug a different problem). Looking at the packets it seems that the "protocol" (first byte after the ethertype) field in the packet is `23`. Which is not a documented value for that field, at least in the documentation I 've been able to find up to now.

http://openrrcp.org.ru/download/datasheets/RTL8316B_Datasheet_1.0.pdf says `RRCP = 01`, `REP = 02`, `network loop detection = 03`. Of course that datasheet if for RTL8316B so if indeed Zyxel uses RTL8370N it might differ. But the datasheets for `8326`, `8326S`, `8324P` specify the same values so I am inclined to believe they don't change. Even `8324` which according to the datasheet does not have RRCP support, has REP and network loop detection with the same values.

That being said, I 've been unable to find a datasheet for `RTL8370N`. http://www.realtek.com/products/productsView.aspx?Langid=1&PNid=18&PFid=43&Level=5&Conn=4&ProdID=270 says that Loop detection is supported but says nothing about RRCP or REP. 

According to https://kb.zyxel.com/KB/searchArticle!viewDetail.action?articleOid=012022&lang=EN it's loop detect. But the number  this goes against the above document (23 != 03). Not that this says much. All in all, my impression is that this chipset does not support fulRRCP but just the network loop detection function. I 'd love to be proved wrong though.

**Comment by samm-git** [comment]
Thank you for reply, probably not possible :( closing for now.
