### ISSUE TITLE
0x23 protocol info?

### ISSUE THREAD

**Issue by allenluce** [illarionov/OpenRRCP#6]
I'm seeing packets like this (from an RTL8305NB):
```
09:15:14.290876 52:54:4c:83:09:e0 > ff:ff:ff:ff:ff:ff, ethertype RRCP (0x8899), length 60: 52:54:4c:83:09:e0 > ff:ff:ff:ff:ff:ff, RRCP-0x23 query
        0x0000:  ffff ffff ffff 5254 4c83 09e0 8899 2300  ......RTL.....#.
        0x0010:  0000 823e fc8a f4f6 0000 0000 0000 0000  ...>............
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000 0000 0000 0000 0000 0000            ............
```
I see from #3 that there's no documentation on `0x23`, at least there wasn't at the time. Have there been any new discoveries since?

**Comment by allenluce** [comment]
Seems it is published. From the [RTL8305NB-CG](http://pdf.51wr.com/uploadpdf/REALTEK/RTL8305NB-CG_datasheet_1242454/202725/RTL8305NB-CG_datasheet.pdf) datasheet, it's a loop detection packet:

![Screen Shot 2019-07-02 at 9 43 42 AM](https://user-images.githubusercontent.com/4258048/60530581-ea8e9980-9cad-11e9-9422-c681c4b210ab.png)

**Comment by cpatulea** [comment]
I've got a Cisco SG110D-08 which sends packets like this (one per second):
```
17:48:58.464710 28:<snip>:6b > ff:ff:ff:ff:ff:ff, RLDP
	0x0000:  2374 c68a 9cb5 e5__ ____ ____ __03 2020  #t..........k...
	0x0010:  2020 2020 2020 2020 2020 2020 2020 2020  ................
	0x0020:  2020 2020 2020 2020 2020 2020 2020       ..............
```

`__` was my mac - redacted.
